# Basic Data Exploration and Cleaning using Pandas

## Dataset
- **Source:** Kaggle - Shopping Dataset
- **File Used:** Combined_dataset.csv

## Objective
Learn Python basics and perform basic data exploration 
and cleaning using Pandas.

## Steps Performed

### 1. Loaded Dataset
- Loaded CSV into a Pandas DataFrame using pd.read_csv()

### 2. Explored Data
- Used head(), tail(), shape, columns, dtypes, info(), describe()
- Dataset contains product listings similar to Amazon/Flipkart

### 3. Handled Missing Values
- Found missing values in: what_customers_said (4), 
  seller_name (4), seller_information (4), variations (1)
- Filled text columns with placeholder values like 
  'No Review', 'Unknown Seller', 'No Info', 'No Variation'

### 4. Filtered & Selected Data
- Filtered products with rating > 4
- Filtered discounted products
- Selected important columns only

### 5. Removed Duplicates
- Checked for duplicates using drop_duplicates()
- Result: 0 duplicates found, data was already clean

### 6. Created Derived Column
- Dataset had no quantity column (product listing dataset)
- Simulated quantity column with random values (1-10)
- Created: total_amount = final_price × quantity

### 7. Saved Cleaned Dataset
- Saved as: cleaned_shopping_dataset.csv
- Used index=False to avoid extra index column

## Output Files
- data_cleaning.ipynb (this notebook)
- cleaned_shopping_dataset.csv

## Key Findings
- Dataset is a product listing catalog (not sales data)
- Prices stored as strings with ₹ symbol — cleaned to float
- No duplicate records found
- total_amount column successfully created after price cleaning

In [3]:
import pandas as pd

df = pd.read_csv('archive/backpacks.csv')

print("Dataset loaded successfully!")
print(df.head())

Dataset loaded successfully!
   product_id           title                         product_description  \
0     8376765     Lino Perros              Women Navy Blue Solid Backpack
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack

   rating  ratings_count  initial_price  discount  final_price currency  \
0     3.8             15         3995.0      58.0  "₹3,995.00"      INR
1     4.5             67         2899.0      35.0  "₹2,899.00"      INR
2     4.4            226         2999.0      65.0  "₹2,999.00"      INR
3     4.4           1052         1675.0      52.0  "₹1,675.00"      INR

                                              images  ...  \
0  http://assets.myntassets.com/assets/images/837...  ...
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...

                                     amount_of_stars what_customers_said  \
0  {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN

  seller_name                 sizes  \
0         NaN  [{"size":"Onesize"}]
1         NaN  [{"size":"Onesize"}]
2         NaN        [{"size":"S"}]
3         NaN  [{"size":"Onesize"}]

                                              videos  seller_information  \
0                              ["rw-8376765_cae700"]                 NaN
1                              ["rw-9136281_cae700"]                 NaN
2  ["https://videos.myntassets.com/assets/videos/...                 NaN
3  ["https://videos.myntassets.com/assets/videos/...                 NaN

            variations best_offer  \
0                 [{}]         {}
1              [{},{}]         {}
2  [{},{},{},{},{},{}]         {}
3                  NaN         {}

                                         more_offers   category
0  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...  backpacks

[4 rows x 24 columns]

In [4]:
# How many rows and columns?
print("Shape:", df.shape)

# What are the column names?
print("\nColumns:", df.columns.tolist())

# What type of data is in each column?
print("\nData Types:")
print(df.dtypes)

# Full overview
print("\nFull Info:")
df.info()

# Statistical summary (min, max, average, etc.)
print("\nStatistics:")
df.describe()

Shape: (4, 24)

Columns: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

Data Types:
product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said       float64
seller_name               float64
sizes                         str
videos                        str
seller_information        float64
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

Full Info:
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              4 non-null      int64
 1   title                   4 non-null      str
 2   product_description     4 non-null      str
 3   rating                  4 non-null      float64
 4   ratings_count           4 non-null      int64
 5   initial_price           4 non-null      float64
 6   discount                4 non-null      float64
 7   final_price             4 non-null      str
 8   currency                4 non-null      str
 9   images                  4 non-null      str
 10  delivery_options        4 non-null      str
 11  product_details         4 non-null      str
 12  breadcrumbs             4 non-null      str
 13  product_specifications  4 non-null      str
 14  amount_of_stars         4 non-null      str
 15  what_customers_said     0 non-null      float64
 16  seller_name             0 non-null      float64
 17  sizes                   4 non-null      str
 18  videos                  4 non-null      str
 19  seller_information      0 non-null      float64
 20  variations              3 non-null      str
 21  best_offer              4 non-null      str
 22  more_offers             4 non-null      str
 23  category                4 non-null      str
dtypes: float64(6), int64(2), str(16)
memory usage: 900.0 bytes

Statistics:

,product_id,rating,ratings_count,initial_price,discount,what_customers_said,seller_name,seller_information
count,4.000000e+00,4.000000,4.000000,4.000000,4.000000,0.0,0.0,0.0
mean,9.130937e+06,4.275000,340.000000,2892.000000,52.500000,NaN,NaN,NaN
std,6.658103e+06,0.320156,483.078324,950.297497,12.819256,NaN,NaN,NaN
min,1.376949e+06,3.800000,15.000000,1675.000000,35.000000,NaN,NaN,NaN
25%,6.626811e+06,4.250000,54.000000,2593.000000,47.750000,NaN,NaN,NaN
50%,8.756523e+06,4.400000,146.500000,2949.000000,55.000000,NaN,NaN,NaN
75%,1.126065e+07,4.425000,432.500000,3248.000000,59.750000,NaN,NaN,NaN
max,1.763375e+07,4.500000,1052.000000,3995.000000,65.000000,NaN,NaN,NaN

In [5]:
# First, check HOW MANY missing values are in each column
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       4
seller_name               4
sizes                     0
videos                    0
seller_information        4
variations                1
best_offer                0
more_offers               0
category                  0
dtype: int64

In [6]:
# Fill text/string columns with a placeholder word
df['what_customers_said'] = df['what_customers_said'].fillna('No Review')
df['seller_name'] = df['seller_name'].fillna('Unknown Seller')
df['seller_information'] = df['seller_information'].fillna('No Info')
df['variations'] = df['variations'].fillna('No Variation')

# Verify - all should show 0 now
print("After handling missing values:")
print(df.isnull().sum())

After handling missing values:
product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [7]:
print(df.columns.tolist())

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [8]:
# Filter 1: Show products with rating greater than 4
high_rated = df[df['rating'] > 4]
print("High rated products (rating > 4):")
print(high_rated.shape)  # how many rows matched
print(high_rated[['title', 'rating', 'final_price']].head())

High rated products (rating > 4):
(3, 24)
            title  rating  final_price
1  Tommy Hilfiger     4.5  "₹2,899.00"
2           Lavie     4.4  "₹2,999.00"
3          F Gear     4.4  "₹1,675.00"

In [9]:
# Filter 2: Show products that have a discount
discounted = df[df['discount'] > 0]
print("\nDiscounted products:")
print(discounted.shape)
print(discounted[['title', 'discount', 'final_price']].head())

Discounted products:
(4, 24)
            title  discount  final_price
0     Lino Perros      58.0  "₹3,995.00"
1  Tommy Hilfiger      35.0  "₹2,899.00"
2           Lavie      65.0  "₹2,999.00"
3          F Gear      52.0  "₹1,675.00"

In [10]:
# Select only important columns
important_cols = df[['product_id', 'title', 'rating', 'initial_price', 'final_price', 'discount', 'category']]

print("Selected columns only:")
print(important_cols.head(10))

Selected columns only:
   product_id           title  rating  initial_price  final_price  discount  \
0     8376765     Lino Perros     3.8         3995.0  "₹3,995.00"      58.0
1     9136281  Tommy Hilfiger     4.5         2899.0  "₹2,899.00"      35.0
2    17633752           Lavie     4.4         2999.0  "₹2,999.00"      65.0
3     1376949          F Gear     4.4         1675.0  "₹1,675.00"      52.0

    category
0  backpacks
1  backpacks
2  backpacks
3  backpacks

In [11]:
# Show title, price, rating of only high-rated products
result = df[df['rating'] > 4][['title', 'rating', 'final_price']]
print(result.head(10))

            title  rating  final_price
1  Tommy Hilfiger     4.5  "₹2,899.00"
2           Lavie     4.4  "₹2,999.00"
3          F Gear     4.4  "₹1,675.00"

In [12]:
# Count how many duplicate rows exist
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [15]:
df = pd.read_csv('archive/Combined_dataset.csv')

print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

Shape: (1000, 24)

Columns: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

First 5 rows:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [13]:
print(df.columns.tolist())

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [16]:
# Check if 'quantity' column is there
if 'quantity' in df.columns:
    print("✅ quantity column EXISTS!")
else:
    print("❌ No quantity column")
    
print(df.columns.tolist())

❌ No quantity column
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [17]:
import numpy as np

# Create quantity column (simulated - 1 to 10 units)
np.random.seed(42)
df['quantity'] = np.random.randint(1, 11, size=len(df))

# Create total_amount = final_price × quantity
df['total_amount'] = df['final_price'] * df['quantity']

# Verify
print("✅ New columns created!")
print(df[['title', 'final_price', 'quantity', 'total_amount']].head(10))

✅ New columns created!
            title  final_price  quantity  \
0     Lino Perros  "₹3,995.00"         7
1  Tommy Hilfiger  "₹2,899.00"         4
2           Lavie  "₹2,999.00"         8
3          F Gear  "₹1,675.00"         5
4       MYTRIDENT  "₹2,899.00"         7
5             H&M  "₹1,399.00"        10
6      AVI Living  "₹1,399.00"         3
7         My Room  "₹2,999.00"         7
8         My Room  "₹2,999.00"         8
9      Story@home  "₹2,199.00"         5

                                        total_amount
0  "₹3,995.00""₹3,995.00""₹3,995.00""₹3,995.00""₹...
1       "₹2,899.00""₹2,899.00""₹2,899.00""₹2,899.00"
2  "₹2,999.00""₹2,999.00""₹2,999.00""₹2,999.00""₹...
3  "₹1,675.00""₹1,675.00""₹1,675.00""₹1,675.00""₹...
4  "₹2,899.00""₹2,899.00""₹2,899.00""₹2,899.00""₹...
5  "₹1,399.00""₹1,399.00""₹1,399.00""₹1,399.00""₹...
6                  "₹1,399.00""₹1,399.00""₹1,399.00"
7  "₹2,999.00""₹2,999.00""₹2,999.00""₹2,999.00""₹...
8  "₹2,999.00""₹2,999.00""₹2,999.00""₹2,999.00""₹...
9  "₹2,199.00""₹2,199.00""₹2,199.00""₹2,199.00""₹...

### Note on total_amount column

This dataset is a product listing dataset (similar to Amazon/Flipkart catalog).
It does not contain a quantity column as products are listed individually.

To fulfil the assignment requirement of:
total_amount = price × quantity

We simulated a quantity column with random values (1–10) representing
hypothetical units sold per product.

Formula used: total_amount = final_price × quantity

In [18]:
print(df['final_price'].dtype)
print(df['final_price'].head())

str
0    "₹3,995.00"
1    "₹2,899.00"
2    "₹2,999.00"
3    "₹1,675.00"
4    "₹2,899.00"
Name: final_price, dtype: str

In [19]:
# Remove ₹ symbol, commas, quotes and convert to float
df['final_price_clean'] = df['final_price'].astype(str)
df['final_price_clean'] = df['final_price_clean'].str.replace('₹', '', regex=False)
df['final_price_clean'] = df['final_price_clean'].str.replace(',', '', regex=False)
df['final_price_clean'] = df['final_price_clean'].str.replace('"', '', regex=False)
df['final_price_clean'] = df['final_price_clean'].str.strip()
df['final_price_clean'] = pd.to_numeric(df['final_price_clean'], errors='coerce')

print("Cleaned prices:")
print(df['final_price_clean'].head(10))
print("Data type:", df['final_price_clean'].dtype)

Cleaned prices:
0    3995.0
1    2899.0
2    2999.0
3    1675.0
4    2899.0
5    1399.0
6    1399.0
7    2999.0
8    2999.0
9    2199.0
Name: final_price_clean, dtype: float64
Data type: float64

In [20]:
df['total_amount'] = df['final_price_clean'] * df['quantity']

print("\n✅ total_amount created correctly!")
print(df[['title', 'final_price_clean', 'quantity', 'total_amount']].head(10))

✅ total_amount created correctly!
            title  final_price_clean  quantity  total_amount
0     Lino Perros             3995.0         7       27965.0
1  Tommy Hilfiger             2899.0         4       11596.0
2           Lavie             2999.0         8       23992.0
3          F Gear             1675.0         5        8375.0
4       MYTRIDENT             2899.0         7       20293.0
5             H&M             1399.0        10       13990.0
6      AVI Living             1399.0         3        4197.0
7         My Room             2999.0         7       20993.0
8         My Room             2999.0         8       23992.0
9      Story@home             2199.0         5       10995.0

In [21]:
# Final check - see what your cleaned dataframe looks like
print("Final Shape:", df.shape)
print("\nColumns in cleaned dataset:", df.columns.tolist())
print("\nAny missing values left?")
print(df.isnull().sum())

Final Shape: (1000, 27)

Columns in cleaned dataset: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category', 'quantity', 'total_amount', 'final_price_clean']

Any missing values left?
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
quantity                    0
total_amount                0
final_price_clean           0
dtype: int64

In [22]:
# Save the cleaned dataset as a new CSV file
df.to_csv('cleaned_shopping_dataset.csv', index=False)

print("✅ File saved successfully!")
print("Filename: cleaned_shopping_dataset.csv")
print("Total rows saved:", len(df))
print("Total columns saved:", len(df.columns))

✅ File saved successfully!
Filename: cleaned_shopping_dataset.csv
Total rows saved: 1000
Total columns saved: 27

In [23]:
import os

# Check if file exists
if os.path.exists('cleaned_shopping_dataset.csv'):
    size = os.path.getsize('cleaned_shopping_dataset.csv')
    print(f"✅ File exists! Size: {size/1024:.2f} KB")
else:
    print("❌ File not found - run the save command again")

✅ File exists! Size: 5398.46 KB